apiVersion: v1
kind: Service
metadata:
  name: opendjuser-node2
  labels:
    name: opendjuser-node2
    app: opendjuser-node2
spec:
  clusterIP: None
  ports:
  - port: 1389
    name: ldap
  - port: 1636
    name: ldaps
  - port: 4444
    name: dj-admin
  - port: 8989
    name: replication
  selector:
    app: opendjuser-node2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
