apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: opendjuser
spec:
  serviceName: opendjuser
  replicas: 1
  template:
    metadata:
      labels:
        app: opendjuser-ha
    spec:
      containers:
      - name: opendjuser
        image: tnstamp/opendjuser:v0.1
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 1
            memory: 3Gi
          requests:
            cpu: 1
            memory: 1Gi
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 1636
          name: ldaps
        - containerPort: 4444
          name: djadmin
        - containerPort: 8989
          name: replication
      imagePullSecrets:
      - name: myregistrykey
