apiVersion: v1
kind: Service
metadata:
  name: opendjuser
  labels:
    name: opendjuser
    app: opendjuser
spec:
  clusterIP: None
  ports:
  - port: 1389
    name: ldap
  - port: 1636
    name: ldaps
  - port: 4444
    name: dj-admin
  - port: 8989
    name: replication
