apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: opendjproxy
spec:
#  serviceName: opendjproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: opendjproxy-ha
    spec:
      imagePullSecrets:
      - name: myregistrykey
      containers:
      - name: opendjproxy
        image: tnstamp/opendjproxy:0.2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 0.5
            memory: 0.5Gi
          requests:
            cpu: 0.5
            memory: 0.5Gi
        ports:
        - containerPort: 1389
          name: ldap
        - containerPort: 1636
          name: ldaps
        - containerPort: 4444
          name: djadmin
        - containerPort: 8989
          name: replication
